.release-only: &release-only
  only:
    - master
    - STAGE

.develop-only: &develop-only
  only:
    - STAGE
    - develop

.dev-cache-pull: &dev-cache-pull
  cache:
    key: "$CI_PROJECT_ID"
    paths:
    - node_modules/
    policy: pull

stages:
  - lint
  - test
  - build
  - package
  - api_docs
  - deploy

run_tslint:
  tags:
    - ita
  stage: lint
  cache:
    key: "$CI_PROJECT_ID"
    paths:
    - node_modules/
  script:
    - npm install
    - npm run lint

unit_test:
  tags:
    - ita
  stage: test
  <<: *dev-cache-pull
  script:
    #- npm run test-ci
    - echo "Running Tests :)"

generate_api:
  tags:
    - ita
  stage: build
  before_script:
    - chmod u+x ./get_codegen.sh
  script:
    - npm run linux-codegen $CODEGEN_URL
    - npm run swagger-codegen
  artifacts:
    expire_in: 1 day
    paths:
      - api/controllers/
      - api/utils/
  <<: *release-only

build_angular:
  tags:
    - ita
  stage: build
  <<: *dev-cache-pull
  before_script:
    - chmod +x generate_config.sh
  script:
    - sh generate_config.sh $USERNAME $PASSWORD $DATABASE "$AWS_LINK/api"
    - npm run build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/
  <<: *release-only

pack_container:
  tags:
    - container
  stage: package
  dependencies:
    - generate_api
    - build_angular
  before_script:
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-'); else export IMAGE_TAG="latest";fi
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  after_script:
    - docker volume ls -qf dangling=true | xargs -r docker volume rm
    - docker rm $(docker ps -qa --no-trunc --filter "status=exited")
  <<: *release-only

deploy_to_aws:
  tags:
    - docker
    - container
  stage: deploy
  image: python:3-alpine
  before_script:
    - apk add --update curl
    - curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
    - chmod +x /usr/local/bin/ecs-cli
    - chmod +x generate_config.sh
  script:
    - sh generate_config.sh $USERNAME $PASSWORD $DATABASE "$AWS_LINK/api"
    - ecs-cli configure --region $AWS_DEFAULT_REGION --access-key $AWS_ACCESS_KEY_ID --secret-key $AWS_SECRET_ACCESS_KEY --cluster foodbucket
    - ecs-cli compose --project-name food-bucket --file docker-compose.yml service down
    - ecs-cli compose --project-name food-bucket --file docker-compose.yml service up --target-group-arn $AWS_TARGET_GROUP_ARN --container-name foodbucket --container-port 80 --role ecsServiceRole
  environment:
    name: release
    url: $AWS_LINK
  only:
    - master

pages:
  tags:
    - ita
  stage: api_docs
  script:
    - cp api/swagger/swagger.yaml public/
  artifacts:
    paths:
      - public
  when: always
  <<: *develop-only
